feat: Execute a shell command in scope of a project
microsoft/rushstack pull request #3862
Opened 2022-12-21 08:38 UTC by sherlockfeng

## Summary
Execute a shell command in scope of a project

## Details
In command-line.json
{
  "commands": [
    {
      "name": "migration",
      "commandKind": "bulk",
      "shellCommand": "node $RUSH_REPO_ROOT/scripts/migration",
    }
  ]
}
Run rush migration, rush will execute node $RUSH_REPO_ROOT/scripts/migration for each project
## How it was tested

2022-12-21 09:21 UTC, chengcyber requested changes

2022-12-21 09:21 UTC, chengcyber commented on libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts
> +  const rawCommand: string | undefined | null = scripts?.[commandToRun] ?? shellCommand;
If i understand the design correctly, should it be `shellCommand ?? scripts?.[commandToRun]`?

2022-12-21 09:21 UTC, chengcyber commented on libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts
> +          commandToRun: phase.shellCommand || commandToRun || '',
Since `shellCommand` has been passed to `getScriptToRun`, it may better to leave this block of logic unchanged.

2022-12-23 05:52 UTC, elliot-nelson commented
It looks like the goal here is to define bulk commands (commands that Rush will facilitate running for you on every project), without having to define a corresponding script on every project. It's like "applying" a custom script to every project.

I feel like the natural progression for such a custom script, though, is like this:

1. Someone throws a few lines into a javascript file
2. The file expands over time to include new corner cases
3. Eventually, a single nodejs script isn't good enough; you want to rewrite it in TypeScript, or it needs some dependencies, so you convert it into a project in your monorepo
4. Rush has a solution for this: you publish your project to your private registry and create an autoinstaller for it

If we're going to begin adding a way to run a "generic CLI script" on bulk-type projects, I think the logical conclusion is that bulk-type projects also need to support autoinstallers, like global commands do.

 - Could autoinstaller be added to bulk commands? Would that make sense in all cases?
 - If not, could it be added only if "shellCommand" is used?
 - If not, should this actually be a totally separate type -- `bulkScript` instead of `bulk`, for example

2022-12-23 08:33 UTC, sherlockfeng commented
The background of this pr is [[rush] Execute a shell command in scope of a project. · Issue #3819 · microsoft/rushstack](https://github.com/microsoft/rushstack/issues/3819)

This feature mainly wants to  run a script in **scope of a project**.

In a certain scope, there is  a better chance this script won't get complicated like js -> ts -> autoinstaller ^_^

For example, if we upgrade a lib package, maybe we will to make some simple changes to projects that depend on this lib through a script or just some shell command.Next time we can completely update the contents of the script to achieve the same goal.

Generally speaking, this ability is more suitable for some less complex needs. It also makes sense for autoinstaller to add bulk type, but can it be done in another pr?
I'm not a native English speaker, so the tone may not be soft.but trust me, I didn't mean to.

2023-01-02 17:28 UTC, elliot-nelson commented
Sounds good @sherlockfeng ! I agree that not everything has to happen in the first PR, I just want to make sure the roadmap to full "generic script execution" is clear, so we can make sure we aren't getting boxed into corners.

The full roadmap to coherent "bulk shell commands" probably looks like:

(1) Support for `shellCommand` in `bulk` commands (presence of `shellCommand` overrides the script name)
(2) Support for `shellCommand` in `phase` definitions (presence of `shellCommand` overrides the phase name)
(3) Add optional auto-installer support for both `bulk` command and `phase` definitions.

(I'd be interested in any thoughts @D4N14L has -- especially the idea that maybe we'd support a phase that requires an autoinstall weaved into a phased operation.)

2023-01-03 05:15 UTC, sherlockfeng commented
I will follow this roadmap to implement "generic script execution", also added this roadmap under the question https://github.com/microsoft/rushstack/issues/3819

2023-01-29 03:20 UTC, octogonz commented
Sorry this PR was overlooked for so long. 🙂🙏  

I merged from `main` and pushed some doc improvements. LGTM

2023-01-29 03:20 UTC, octogonz approved these changes

2023-01-29 05:34 UTC, octogonz commented
(@sherlockfeng will do a final test pass, then we'll merge+publish this.)

2023-01-29 12:09 UTC, sherlockfeng commented
@octogonz everything looks fine~

2023-01-29 19:44 UTC, merged

2023-01-29 20:24 UTC, octogonz commented
🚀 Released with Rush 5.90.0

2023-01-29 21:38 UTC, octogonz commented
Docs update: https://github.com/microsoft/rushstack-websites/pull/125